name: CI - DevTask API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build da imagem Docker
        run: docker build -t devtask-api .

      - name: Testar conteiner
        run: |
          docker run -d -p 3000:3000 --name test-container devtask-api
          sleep 5
          curl http://localhost:3000
          docker stop test-container